# wap to print out the results of different arithmatic operater (+,-,*,/,%) perform using 2 no (say 20 ,10)
a = float(input("enter a 1st number :"))
b = float(input("enter a 2nd number :"))
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a%b)